// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jugrirhdeenvivofbkpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1Z3JpcmhkZWVudml2b2Zia3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwNDMxNTgsImV4cCI6MjA5MjYxOTE1OH0.FHAdDkSUVJZtzDX7aUYmb6x_2AceoQn4KnhXUvGb3D4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});