// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czbxezhphmkjczwgqall.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6YnhlemhwaG1ramN6d2dxYWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwMzg3MTEsImV4cCI6MjA5MjYxNDcxMX0.rq8Yq7666ilCrxepJ_RIb0W0aJu6WuB_eIdhISix8Yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});